name: "Builds Sanity Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-squbi:
    name: "Release Pivit"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: "Install golang"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y libpcsclite-dev
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Build and run"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          make build
          # Run simple test
          gunzip -c build/pivit-*.gz > build/pivit
          chmod +x build/pivit
          ./build/pivit --help
          if ${{ matrix.os == 'macos-latest' }}; then
            # Cross compile for darwin-arm64 and run simple test
            make build GOARCH=arm64
            gunzip -c build/pivit-darwin-arm64.gz > build/pivit
            file build/pivit
          fi
